### PR TITLE
Changed old string formatting to fstrings

### LINKED ISSUE #72: Use f strings instead of old style format
Need to update to better python

### PR DESCRIPTION
**Pull request by jbx09**
Fixes #72 

@ottobackwards  Changed all old string formatting used in print and logging statements to new fstrings style.

Note:
Changed a variable name in one of the logging statement in https://github.com/palindromicity/dotifi/blob/main/dotifi/configuration/load.py#L10 from `config` (which is a object) to `configuration_file_path` which looked appropriate. Please review.

```
❯ poetry run pytest -v
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.8.5, pytest-4.6.11, py-1.9.0, pluggy-0.13.1 -- /Users/balaji/anaconda3/envs/dotifi/bin/python
cachedir: .pytest_cache
rootdir: /Users/balaji/ws/git_works/dotifi
plugins: mock-3.2.0
collected 10 items

tests/test_dotifi.py::test_version PASSED                                                                                                                                                                                              [ 10%]
tests/integration/test_secure.py::test_happy_path SKIPPED                                                                                                                                                                              [ 20%]
tests/unit_tests/configuration/test_dotifi_util_configuration.py::test_load_sample_configuration PASSED                                                                                                                                [ 30%]
tests/unit_tests/configuration/test_dotifi_util_configuration.py::test_load_env_configuration PASSED                                                                                                                                   [ 40%]
tests/unit_tests/nifi/test_mock_generate.py::test_happy_path[path_arg0] PASSED                                                                                                                                                         [ 50%]
tests/unit_tests/nifi/test_mock_generate.py::test_start_pg[path_arg0] PASSED                                                                                                                                                           [ 60%]
tests/unit_tests/nifi/test_mock_generate.py::test_rpg_attribute_override[path_arg0] PASSED                                                                                                                                             [ 70%]
tests/unit_tests/nifi/test_mock_generate.py::test_processor_attribute_override[path_arg0] PASSED                                                                                                                                       [ 80%]
tests/unit_tests/nifi/test_mock_generate.py::test_graph_template[path_arg0] PASSED                                                                                                                                                     [ 90%]
tests/unit_tests/nifi/test_mock_generate.py::test_pg_template[path_arg0] PASSED                                                                                                                                                        [100%]

==================================================================================================== 9 passed, 1 skipped in 0.83 seconds =====================================================================================================
```

### CODE REVIEW

**Comment by ottobackwards** [comment]
Thanks!  I'll take a look.
As you can see above, the linting failed though.

Can you address that?
if you install [pre-commit](https://pre-commit.com)  and do the pre-commit install, you can run the linters and it looks like they will fix the issue for you.
You can then do `git add` `git commit -m ` `git push xxx` to fix the issue

**Comment by jbx09** [comment]
@ottobackwards  Sure, will check the linting issues and update. Thanks for the tip.

**Comment by ottobackwards** [comment]
I need to fix the actions

**Comment by ottobackwards** [comment]
Thank you for the contribution!

**Comment by ottobackwards** [comment]
@jbx09 palindromicity.slack.com if you would like

**Comment by jbx09** [comment]
> @jbx09 palindromicity.slack.com if you would like

@ottobackwards I am not able to join the palindromicity.slack.com, do I need to be added to workspace?, if so my email id is `balajimails09@gmail.com`

**Pull request merged**
